name: Build Docker
description: Build and push Docker image to GitHub Container Registry

inputs:
  app:
    description: "Application name to build"
    required: true
  registry:
    description: "Docker registry"
    required: false
    default: "ghcr.io"
  image-name:
    description: "Base image name"
    required: true
  docker-username:
    description: "Docker registry username"
    required: true
  docker-password:
    description: "Docker registry password or token"
    required: true

outputs:
  image-tags:
    description: "Generated image tags"
    value: ${{ steps.meta.outputs.tags }}
  image-digest:
    description: "Image digest"
    value: ${{ steps.build.outputs.digest }}

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}/${{ inputs.app }}
        tags: |
          type=ref,event=branch
          type=sha,prefix=
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ./apps/${{ inputs.app }}
        file: ./apps/${{ inputs.app }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
