name: Setup Expo
description: Setup Expo and EAS CLI with authentication

inputs:
  expo-token:
    description: "Expo authentication token"
    required: true
  eas-version:
    description: "EAS CLI version"
    required: false
    default: "latest"

runs:
  using: composite
  steps:
    - name: Setup Expo and EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: ${{ inputs.eas-version }}
        token: ${{ inputs.expo-token }}
