name: Build EAS
description: Build and optionally submit mobile app using Expo EAS (local build, requires macOS)

inputs:
  expo-token:
    description: "Expo authentication token"
    required: true
  working-directory:
    description: "Working directory for the mobile app"
    required: false
    default: "./apps/mobile-app"
  platform:
    description: "Platform to build (ios, android, all)"
    required: false
    default: "ios"
  auto-submit:
    description: "Auto submit to stores after build"
    required: false
    default: "false"
  profile:
    description: "EAS build profile"
    required: false
    default: "development"
  vault-url:
    description: "OpenBao/Vault server URL"
    required: false
    default: ""
  vault-token:
    description: "OpenBao/Vault authentication token"
    required: false
    default: ""

runs:
  using: composite
  steps:
    # Required for EAS CLI authentication in CI
    - name: Setup Expo and EAS
      uses: ./.github/actions/setup-expo
      with:
        expo-token: ${{ inputs.expo-token }}

    # Fetch iOS certs from OpenBao and create credentials.json
    - name: Fetch iOS certificates
      if: (inputs.platform == 'ios' || inputs.platform == 'all') && inputs.vault-url != ''
      uses: ./.github/actions/fetch-ios-certs
      with:
        vault-url: ${{ inputs.vault-url }}
        vault-token: ${{ inputs.vault-token }}
        working-directory: ${{ inputs.working-directory }}

    # --local: build on the runner (macOS) instead of EAS cloud
    - name: Build iOS
      if: inputs.platform == 'ios' || inputs.platform == 'all'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm install -g eas-cli-local-build-plugin
        eas build --platform ios --profile ${{ inputs.profile }} --non-interactive --local --output ./build.ipa

    - name: Upload iOS artifact
      if: inputs.platform == 'ios' || inputs.platform == 'all'
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ${{ inputs.working-directory }}/build.ipa
        retention-days: 14

    - name: Submit iOS
      if: (inputs.platform == 'ios' || inputs.platform == 'all') && inputs.auto-submit == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: eas submit --platform ios --path ./build.ipa --non-interactive

    - name: Build Android
      if: inputs.platform == 'android' || inputs.platform == 'all'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        eas build --platform android --profile ${{ inputs.profile }} --non-interactive --local --output ./build.aab

    - name: Upload Android artifact
      if: inputs.platform == 'android' || inputs.platform == 'all'
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: ${{ inputs.working-directory }}/build.aab
        retention-days: 14

    - name: Submit Android
      if: (inputs.platform == 'android' || inputs.platform == 'all') && inputs.auto-submit == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: eas submit --platform android --path ./build.aab --non-interactive
