name: Build EAS
description: Build and submit mobile app using Expo EAS

inputs:
  expo-token:
    description: "Expo authentication token"
    required: true
  working-directory:
    description: "Working directory for the mobile app"
    required: false
    default: "./apps/mobile-app"
  platform:
    description: "Platform to build (ios, android, all)"
    required: false
    default: "all"
  auto-submit:
    description: "Auto submit to stores"
    required: false
    default: "true"
  profile:
    description: "EAS build profile"
    required: false
    default: "production"
  vault-url:
    description: "OpenBao/Vault server URL"
    required: false
    default: ""
  vault-token:
    description: "OpenBao/Vault authentication token"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.expo-token }}

    - name: Fetch iOS certificates from OpenBao
      if: |
        (inputs.platform == 'ios' || inputs.platform == 'all') && 
        inputs.vault-url != ''
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ inputs.vault-url }}
        token: ${{ inputs.vault-token }}
        secrets: |
          kv/data/distribution p12_b64 | IOS_DIST_CERT_B64 ;
          kv/data/distribution p12_password | IOS_DIST_CERT_P12_PASSWORD ;
          kv/data/distribution provision_b64 | IOS_PROVISION_PROFILE_B64

    - name: Create iOS certs directory
      if: |
        (inputs.platform == 'ios' || inputs.platform == 'all') && 
        inputs.vault-url != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mkdir -p certs/ios

    - name: Save iOS certificates to certs/ios
      if: |
        (inputs.platform == 'ios' || inputs.platform == 'all') && 
        inputs.vault-url != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Décoder les fichiers base64
        echo "$IOS_DIST_CERT_B64" | base64 -d > certs/ios/dist.p12
        echo "$IOS_PROVISION_PROFILE_B64" | base64 -d > certs/ios/profile.mobileprovision
        
        # Vérifier que les fichiers sont créés
        ls -lh certs/ios/

    - name: Create credentials.json
      if: |
        (inputs.platform == 'ios' || inputs.platform == 'all') && 
        inputs.vault-url != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cat > credentials.json << EOF
        {
          "ios": {
            "distributionCertificate": {
              "path": "certs/ios/dist.p12",
              "password": "${IOS_DIST_CERT_P12_PASSWORD}"
            },
            "provisioningProfilePath": "certs/ios/profile.mobileprovision"
          }
        }
        EOF

    - name: Build and submit iOS
      if: inputs.platform == 'ios' || inputs.platform == 'all'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.auto-submit }}" == "true" ]; then
          npx eas build --platform ios --profile ${{ inputs.profile }} --non-interactive --local --auto-submit
        else
          npx eas build --platform ios --profile ${{ inputs.profile }} --non-interactive --local
        fi

    - name: Build and submit Android
      if: inputs.platform == 'android' || inputs.platform == 'all'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.auto-submit }}" == "true" ]; then
          npx eas build --platform android --profile ${{ inputs.profile }} --non-interactive --auto-submit
        else
          npx eas build --platform android --profile ${{ inputs.profile }} --non-interactive
        fi
