name: Build EAS
description: Build and submit mobile app using Expo EAS

inputs:
  expo-token:
    description: "Expo authentication token"
    required: true
  working-directory:
    description: "Working directory for the mobile app"
    required: false
    default: "./apps/mobile-app"
  platform:
    description: "Platform to build (ios, android, all)"
    required: false
    default: "all"
  auto-submit:
    description: "Auto submit to stores"
    required: false
    default: "true"
  profile:
    description: "EAS build profile"
    required: false
    default: "production"
  vault-url:
    description: "OpenBao/Vault server URL"
    required: false
    default: ""
  vault-token:
    description: "OpenBao/Vault authentication token"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup Expo
      uses: ./.github/actions/setup-expo
      with:
        expo-token: ${{ inputs.expo-token }}

    - name: Fetch iOS certificates
      if: |
        (inputs.platform == 'ios' || inputs.platform == 'all') && 
        inputs.vault-url != ''
      uses: ./.github/actions/fetch-ios-certs
      with:
        vault-url: ${{ inputs.vault-url }}
        vault-token: ${{ inputs.vault-token }}
        working-directory: ${{ inputs.working-directory }}

    - name: Install EAS local build plugin
      if: inputs.platform == 'ios' || inputs.platform == 'all'
      shell: bash
      run: npm install -g eas-cli-local-build-plugin

    - name: Build and submit iOS
      if: inputs.platform == 'ios' || inputs.platform == 'all'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.auto-submit }}" == "true" ]; then
          eas build --platform ios --profile ${{ inputs.profile }} --non-interactive --local --auto-submit
        else
          eas build --platform ios --profile ${{ inputs.profile }} --non-interactive --local
        fi

    - name: Build and submit Android
      if: inputs.platform == 'android' || inputs.platform == 'all'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.auto-submit }}" == "true" ]; then
          eas build --platform android --profile ${{ inputs.profile }} --non-interactive --auto-submit
        else
          eas build --platform android --profile ${{ inputs.profile }} --non-interactive
        fi
