import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
	RuntimeConfigProvider,
	type RuntimeConfig,
	SocketProvider,
} from "../src/contexts";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const runtimeConfig: RuntimeConfig = {
		apiUrl: process.env.API_URL ?? "",
		socketUrl: process.env.SOCKET_URL ?? "",
		socketPath: process.env.SOCKET_PATH ?? "",
		desktopSseSubscriptionId: process.env.DESKTOP_SSE_SUBSCRIPTION_ID ?? "",
		mobileSseSubscriptionId: process.env.MOBILE_SSE_SUBSCRIPTION_ID ?? "",
	};

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<RuntimeConfigProvider config={runtimeConfig}>
					<SocketProvider>{children}</SocketProvider>
				</RuntimeConfigProvider>
			</body>
		</html>
	);
}
